Repository WildCodeSchool-2024-09/js-remote-orange-P3-cinestream, pull requests merged in 2025-01, with the labels that each got.

#6 css nav
  README.md
  client/public/images/Cinestream.png
  client/public/images/premium.png
  client/src/components/commun/navBarre/NavBarre.tsx
  client/src/components/commun/navBarre/bntConnection/BntConnection.tsx
  client/src/components/commun/navBarre/bntConnection/bntConnection.css
  client/src/components/commun/navBarre/bntConnection/bntConnection.module.css
  client/src/components/commun/navBarre/bntIncription/BntIncription.tsx
  client/src/components/commun/navBarre/bntIncription/bntIncription.css
  client/src/components/commun/navBarre/bntIncription/bntIncription.module.css
  client/src/components/commun/navBarre/bntRecherche/BntRecherche.tsx
  client/src/components/commun/navBarre/bntRecherche/bntRecherche.css
  client/src/components/commun/navBarre/bntRecherche/bntRecherche.module.css
  client/src/components/commun/navBarre/navBarre.module.css
  client/src/components/utilisateur/home/homeHeader/HomeHeader.tsx
Labels: CONFLICTS

#15 modificaton du pull
  client/package.json
  client/src/components/commun/navBarre/bntConnection/BntConnection.tsx
  client/src/components/utilisateur/home/homeHeader/bntFavorie/BntFavorie.tsx
  client/src/components/utilisateur/home/homeHeader/bntLecture/BntLecture.tsx
  client/src/components/utilisateur/home/homeHeader/desciptionAnonce/DesciptionAnonce.tsx
  client/src/components/utilisateur/home/homeHero/allFilme/AllFilme.tsx
  client/src/components/utilisateur/home/homeHero/categorie/Categorie.tsx
  client/src/components/utilisateur/home/homeHero/categorie/categorie.module.css
  client/src/components/utilisateur/home/homeHero/recent/Recent.tsx
  client/src/components/utilisateur/home/homeHero/topNotes/TopNotes.tsx
  client/src/components/utilisateur/recherche/rechercheHeader/RechercheHeader.tsx
  client/src/components/utilisateur/recherche/rechercheHeader/rechercheHeader.module.css
  client/src/components/utilisateur/recherche/rechercheHero/RechercheHero.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filmComposent/filmComposent.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filmComposent/filmComposent.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/categorie/Categorie.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/categorie/categorie.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/filterBarre.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/filterBarre.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/filterdate/Filterdate.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/filterdate/filterdate.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/recherche/Recherche.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/recherche/recherche.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/type/TypeFiltre.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/type/type.module.css
  client/src/components/utilisateur/recherche/rechercheHero/rechercheHero.module.css
  client/src/pages/utilisateur/recherche/Recherche.tsx
  client/src/pages/utilisateur/recherche/recherche.css
  package-lock.json
  server/bin/admin.json
Labels: ATTENTE_VALIDATION

#19 S02 us16 page gestion serie
  client/src/components/backOffice/adminSeries/crudEpisode/CrudEpisode.module.css
  client/src/components/backOffice/adminSeries/crudEpisode/CrudEpisode.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/InputSaison/InputSaison.module.css
  client/src/components/backOffice/adminSeries/crudEpisode/InputSaison/InputSaison.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/bntAjouterEpisode/BntAjouterEpisode.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/bntAjouterEpisode/bntAjouterEpisode.module.css
  client/src/components/backOffice/adminSeries/crudEpisode/elementCurd/ElementCurd.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/elementCurd/elementCurd.module.css
  client/src/components/backOffice/adminSeries/crudUnisers/CrudEpisode.module.css
  client/src/components/backOffice/adminSeries/crudUnisers/CrudUnivers.tsx
  client/src/components/backOffice/adminSeries/crudUnisers/bntAjouterSerie/BntAjouterSerie.tsx
  client/src/components/backOffice/adminSeries/crudUnisers/bntAjouterSerie/bntAjouterSerie.module.css
  client/src/components/backOffice/adminSeries/crudUnisers/elementCurd/ElementCurd.tsx
  client/src/components/backOffice/adminSeries/crudUnisers/elementCurd/elementCurd.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/InfoGeneral.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/InfoGeneral.tsx.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/bntFermerAdminSerie/BntFermerAdminSerie.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/bntFermerAdminSerie/bntFermerAdminSerie.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/bntFermerCommun/BntFermerCommun.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/bntFermerCommun/bntFermerCommun.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/modalListeCommun/ModalListeCommun.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/modalListeCommun/checkboxModal/CheckboxModal.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/modalListeCommun/checkboxModal/checkboxModal.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/modalListeCommun/modalListeCommun.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/styleListeType.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputCheck/InputCheck.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputCheck/inputCheck.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputDateSerie/InputDateSerie.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputDateSerie/inputDateSerie.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageHaurisontal/InputImageHaurisontal.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageHaurisontal/inputImageHaurisontal.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageVertical/InputImageVertical.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageVertical/inputImageVertical.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputTitreSerie/InputTitreSerie.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputTitreSerie/inputTitreSerie.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/listeCategorie/ListeCategorie.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/listeCategorie/listeCategorie.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/listeProducteur/ListeProducteur.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/listeProducteur/listeProducteur.module.css
  client/src/main.css
  client/src/pages/backOffice/adminSeries/AdminSeries.tsx
  client/src/pages/backOffice/adminSeries/adminSeries.css
  client/src/pages/backOffice/adminSeries/adminSeries.module.css
  client/src/pages/utilisateur/home/home.module.css
Labels: ATTENTE_VALIDATION

#20 création de la page de gestion des episode
  client/src/components/backOffice/adminEpisode/bntFermerAdminEpisode/BntFermerAdminEpisode.tsx
  client/src/components/backOffice/adminEpisode/bntFermerAdminEpisode/bntFermerAdminEpisode.module.css
  client/src/components/backOffice/adminEpisode/inputDescriptionEpisode/InputDescriptionEpisode.tsx
  client/src/components/backOffice/adminEpisode/inputDescriptionEpisode/inputDescriptionEpisode.module.css
  client/src/components/backOffice/adminEpisode/inputImageHaurisontal/InputImageHaurisontal.tsx
  client/src/components/backOffice/adminEpisode/inputImageHaurisontal/inputImageHaurisontal.module.css
  client/src/components/backOffice/adminEpisode/inputLienVideo/InputLienVideo.tsx
  client/src/components/backOffice/adminEpisode/inputLienVideo/inputLienVideo.module.css
  client/src/components/backOffice/adminEpisode/inputTitreEpisode/InputTitreEpisode.tsx
  client/src/components/backOffice/adminEpisode/inputTitreEpisode/inputTitreEpisode.module.css
  client/src/pages/backOffice/adminEpisode/AdminEpisode.tsx
  client/src/pages/backOffice/adminEpisode/adminEpisode.css
  client/src/pages/backOffice/adminEpisode/adminEpisode.module.css
Labels: ATTENTE_VALIDATION

#25 pr du week end bug fix
  client/src/components/backOffice/adminRecherche/listeSeries/ListeSeries.tsx
  client/src/components/backOffice/adminRecherche/listeSeries/filmComposent/FilmComposent.tsx
  client/src/components/backOffice/adminRecherche/listeSeries/filmComposent/filmComposent.module.css
  client/src/components/backOffice/adminRecherche/listeSeries/listeSeries.module.css
  client/src/components/backOffice/adminRecherche/modal/Modal.tsx
  client/src/components/backOffice/adminRecherche/recherche/Recherche.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/bntAjouterEpisode/BntAjouterEpisode.tsx
  client/src/components/backOffice/adminSeries/footerAction/FooterAction.tsx
  client/src/components/backOffice/adminSeries/footerAction/bntAnnuler/BntAnnuler.tsx
  client/src/components/backOffice/adminSeries/footerAction/bntAnnuler/bntAnnuler.module.css
  client/src/components/backOffice/adminSeries/footerAction/bntSaugarder/BntSaugarder.tsx
  client/src/components/backOffice/adminSeries/footerAction/bntSaugarder/bntSaugarder.module.css
  client/src/components/backOffice/adminSeries/footerAction/bntSupprimer/BntSupprimer.tsx
  client/src/components/backOffice/adminSeries/footerAction/bntSupprimer/bntSupprimer.module.css
  client/src/components/backOffice/adminSeries/footerAction/footerAction.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/InfoGeneral.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/modalListeCommun/ModalListeCommun.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/modalListeCommun/checkboxModal/CheckboxModal.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/communInfoGeneral/modalListeCommun/modalListeCommun.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputCheck/InputCheck.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputDateSerie/InputDateSerie.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputTitreSerie/InputTitreSerie.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/listeCategorie/ListeCategorie.tsx
  client/src/components/utilisateur/presentation/presentationHeader/bntEdite/BntEdite.tsx
  client/src/components/utilisateur/presentation/presentationHeader/bntEdite/bntEdite.module.css
  client/src/components/utilisateur/presentation/presentationHeader/bntFavorie/BntFavorie.tsx
  client/src/components/utilisateur/presentation/presentationHeader/bntFavorie/bntFavorie.module.css
  client/src/components/utilisateur/presentation/presentationHeader/bntPartager/BntPartager.tsx
  client/src/components/utilisateur/presentation/presentationHeader/bntPartager/bntPartager.module.css
  client/src/components/utilisateur/presentation/presentationHeader/bntRegarder/BntRegarder.tsx
  client/src/components/utilisateur/presentation/presentationHeader/bntRegarder/bntRegarder.module.css
  client/src/components/utilisateur/presentation/presentationHeader/descriptionPresentation/DescriptionPresentation.tsx
  client/src/components/utilisateur/presentation/presentationHeader/descriptionPresentation/descriptionPresentation.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filmComposent/filmComposent.module.css
  client/src/context/tokenContext.tsx
  client/src/main.tsx
  client/src/pages/backOffice/adminRecherche/AdminRecherche.tsx
  client/src/pages/backOffice/adminSeries/adminSeries.module.css
  server/database/schema.sql
  server/package.json
  server/src/modules/article/articleActions.ts
  server/src/modules/article/articleRepository.ts
  server/src/modules/categorie/categorieActions.ts
  server/src/modules/categorie/categorieRepository.ts
  server/src/modules/item/itemActions.ts
  server/src/modules/item/itemRepository.ts
  server/src/modules/middlewares/autentification.ts
  server/src/modules/serie/serieActions.ts
  server/src/modules/serie/serieRepository.ts
  server/src/modules/utilisateur/utilisateurActions.ts
  server/src/router.ts
Labels: ATTENTE_VALIDATION

#29 uplode image de la serie
  client/src/components/backOffice/adminSeries/footerAction/FooterAction.tsx
  client/src/components/backOffice/adminSeries/footerAction/bntAnnuler/BntAnnuler.tsx
  client/src/components/backOffice/adminSeries/footerAction/bntSaugarder/BntSaugarder.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/InfoGeneral.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/InfoGeneral.tsx.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageHaurisontal/InputImageHaurisontal.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageHaurisontal/inputImageHaurisontal.module.css
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageVertical/InputImageVertical.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputImageVertical/inputImageVertical.module.css
  client/src/components/utilisateur/presentation/presentationHero/PresentationHero.tsx
  client/src/components/utilisateur/presentation/presentationHero/episode/episode.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/Notation.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/CommentaireUtilisateur.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/etoileUtilisateur/EtoileUtilisateur.tsx
  client/src/components/utilisateur/presentation/presentationHero/univers/Univers.tsx
  client/src/components/utilisateur/presentation/presentationHero/univers/univers.module.css
  client/src/pages/backOffice/adminSeries/AdminSeries.tsx
  client/src/pages/backOffice/adminSeries/adminSeries.module.css
  package-lock.json
  server/.gitignore
  server/package.json
  server/src/app.ts
  server/src/modules/article/articleActions.ts
  server/src/modules/article/articleRepository.ts
  server/src/modules/middlewares/autentification.ts
  server/src/modules/middlewares/multer.ts
  server/src/router.ts
Labels: ATTENTE_VALIDATION

#30 S02US27cssPageDetails
  client/src/components/utilisateur/presentation/presentationHero/episode/Episode.tsx
  client/src/components/utilisateur/presentation/presentationHero/episode/episode.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/allCommentaire/AllCommentaire.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/allCommentaire/allCommentaire.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/allCommentaire/allCommentaireComposent/AllCommentaireComposent.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/allCommentaire/allCommentaireComposent/allCommentaireComposent.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/allCommentaire/bntPlus/BntPlus.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/allCommentaire/bntPlus/bntPlus.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/CommentaireUtilisateur.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/bntEnvoyer/BntEnvoyer.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/bntEnvoyer/bntEnvoyer.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/commentaireUtilisateur.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/etoileUtilisateur/EtoileUtilisateur.tsx
  client/src/components/utilisateur/presentation/presentationHero/notation/commentaireUtilisateur/etoileUtilisateur/etoileUtilisateur.module.css
  client/src/components/utilisateur/presentation/presentationHero/notation/notation.module.css
  client/src/components/utilisateur/presentation/presentationHero/univers/Univers.tsx
  client/src/components/utilisateur/recherche/rechercheHero/rechercheHero.module.css
Labels: CONFLICTS_RESOLVED

#32 S02 us29 crud episode
  client/src/components/backOffice/adminEpisode/footerAction/bntAnnuler/BntAnnuler.tsx
  client/src/components/backOffice/adminEpisode/footerAction/bntSaugarder/BntSaugarder.tsx
  client/src/components/backOffice/adminEpisode/footerAction/bntSupprimer/BntSupprimer.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/CrudEpisode.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/InputSaison/InputSaison.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/bntAjouterEpisode/BntAjouterEpisode.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/elementCurd/ElementCurd.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/elementCurd/croixSup/CroixSup.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/elementCurd/flecheBas/FlecheBas.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/elementCurd/flecheHaut/FlecheHaut.tsx
  client/src/main.tsx
  client/src/pages/backOffice/adminEpisode/AdminEpisode.tsx
  server/src/hook/supprimerImage.ts
  server/src/modules/episode/episodeActions.ts
  server/src/modules/episode/episodeRepository.ts
  server/src/modules/episode/saisonRepository.ts
  server/src/modules/serie/serieActions.ts
  server/src/router.ts
Labels: ATTENTE_VALIDATION

#33 premier home page dynamique
  client/src/components/commun/slider/sliderClike.tsx
  client/src/components/utilisateur/home/homeHero/allFilme/AllFilme.tsx
  client/src/components/utilisateur/home/homeHero/allFilme/allFilme.module.css
  client/src/components/utilisateur/home/homeHero/allSerie/AllSerie.tsx
  client/src/components/utilisateur/home/homeHero/allSerie/allSerie.module.css
  client/src/components/utilisateur/home/homeHero/recent/Recent.tsx
  client/src/components/utilisateur/home/homeHero/recent/recent.module.css
  client/src/components/utilisateur/home/homeHero/source/Source.tsx
  client/src/hook/articleRandom.ts
  client/src/main.tsx
  server/database/schema.sql
  server/public/assets/images/favicon.png
  server/public/images/logo_producteur/logo_Netflix.png
  server/public/images/logo_producteur/logo_appelTv.png
  server/public/images/logo_producteur/logo_autre.png
  server/public/images/logo_producteur/logo_canal+.png
  server/public/images/logo_producteur/logo_disney+.png
  server/public/images/logo_producteur/logo_hulu.png
  server/public/images/logo_producteur/logo_myCanal.png
  server/public/images/logo_producteur/logo_primeVideo.png
  server/public/images/logo_producteur/logo_siteInernette.png
  server/public/images/logo_producteur/logo_twitch.png
  server/public/images/logo_producteur/logo_youTube.png
  server/src/app.ts
  server/src/modules/caroussel/carousselActions.ts
  server/src/modules/caroussel/carousselRepository.ts
  server/src/router.ts
Labels: ATTENTE_VALIDATION

#34 S02 us31 fin back office
  client/src/components/backOffice/adminEpisode/inputDescriptionEpisode/InputDescriptionEpisode.tsx
  client/src/components/backOffice/adminEpisode/inputImageHaurisontal/InputImageHaurisontal.tsx
  client/src/components/backOffice/adminEpisode/inputTitreEpisode/InputTitreEpisode.tsx
  client/src/components/backOffice/adminRecherche/bntAjouter/BntAjouter.tsx
  client/src/components/backOffice/adminRecherche/bntAjouter/bntAjouter.module.css
  client/src/components/backOffice/adminRecherche/listeSeries/ListeSeries.tsx
  client/src/components/backOffice/adminRecherche/listeSeries/filmComposent/FilmComposent.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/CrudEpisode.tsx
  client/src/components/backOffice/adminSeries/crudEpisode/elementCurd/ElementCurd.tsx
  client/src/components/backOffice/adminSeries/crudUnisers/CrudUnivers.tsx
  client/src/components/backOffice/adminSeries/crudUnisers/bntAjouterSerie/BntAjouterSerie.tsx
  client/src/components/backOffice/adminSeries/crudUnisers/elementCurd/ElementCurd.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/InfoGeneral.tsx
  client/src/components/backOffice/adminSeries/infoGeneral/inputTitreSerie/InputTitreSerie.tsx
  client/src/pages/backOffice/adminEpisode/AdminEpisode.tsx
  client/src/pages/backOffice/adminRecherche/AdminRecherche.tsx
  client/src/pages/backOffice/adminSeries/AdminSeries.tsx
  server/database/schema.sql
  server/src/modules/crudUnivers/crudUniversAction.ts
  server/src/modules/crudUnivers/crudUniversRepository.ts
  server/src/modules/episode/episodeActions.ts
  server/src/modules/episode/episodeRepository.ts
  server/src/router.ts
Labels: CORRECTIONS_DONE, ATTENTE_VALIDATION

#36 page utilisateur recherche mis en dynamique avec api
  client/src/components/utilisateur/recherche/rechercheHero/RechercheHero.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filmComposent/bntPlus/BntPlus.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filmComposent/bntPlus/bntPlus.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filmComposent/filmComposent.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filmComposent/filmComposent.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/categorie/Categorie.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/categorie/categorie.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/filterBarre.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/filterdate/Filterdate.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/filterdate/filterdate.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/recherche/Recherche.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/recherche/recherche.module.css
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/type/TypeFiltre.tsx
  client/src/components/utilisateur/recherche/rechercheHero/filterBarre/type/type.module.css
  server/src/modules/serie/serieActions.ts
  server/src/modules/serie/serieRepository.ts
  server/src/router.ts
Labels: ATTENTE_VALIDATION
